version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    links:
        - "mongo:mongo"
  mongo:
    image: mongo
    hostname: mongo
    volumes:
      - data:/data/db
    environment:
      -  'MONGODB_USER=user' 
      -  'MONGODB_PASS=password!'
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  mongo-express:
    image: mongo-express
    hostname: mongo-express
    links:
        - "mongo:mongo"
    ports:
        - "8081:8081"
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
      - 'ME_CONFIG_BASICAUTH_USERNAME=user'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=password!'
volumes:
  mongodb:
  mongodb_config: